name: "Upload DA"
description: "Upload the content to DA using IMS token exchange for authentication"
author: "Experience Catalyst"
inputs:
  target:
    description: "The target of the upload. This is the DA URL (see mountpoint)."
    required: true
  content_path:
    description: "The path to the folder containing the da files."
    required: true
  skip_assets:
    description: "Whether to skip assets"
    required: false
    default: false
  operation:
    description: "The operation to perform"
    required: false
    default: upload
outputs:
  paths:
    description: "The list of paths that were uploaded"
  error_message:
env:
  DA_CLIENT_ID:
    description: "Adobe IMS client ID for DA authentication"
    required: true
  DA_CLIENT_SECRET:
    description: "Adobe IMS client secret for DA authentication"
    required: true
  DA_SERVICE_TOKEN:
    description: "Adobe IMS service token (authorization code) for DA authentication"
    required: true
runs:
  using: 'node20'
  main: 'sta-da-helper.js'
